parameters:
    sirian.sphinx.connection.class: Sirian\SphinxBundle\SphinxQL\Connection
    sirian.sphinx.manager.class: Sirian\SphinxBundle\Manager

services:
    sirian.sphinx.manager:
        class: %sirian.sphinx.manager.class%
        arguments:
            - %sirian.sphinx.connections%
            - %sirian.sphinx.default_connection%
        calls:
            - ['setContainer', [@service_container]]

    sirian.sphinx.connection:
        class: %sirian.sphinx.connection.class%
        abstract: true
        calls:
            - ['setStopWatch', [@?debug.stopwatch]]
